"""SSE transport for Phase A.2 queue events (Task B5).

Subscribes to the in-process ``EventBroadcaster`` only — no Redis Pub/Sub
access here. Heartbeats are SSE comments generated by this transport layer.
"""

from __future__ import annotations

import asyncio
import logging
from collections.abc import AsyncIterator
from typing import Annotated

from fastapi import APIRouter, Depends, Request
from starlette.responses import StreamingResponse

from app.auth.dependencies import CurrentUser
from app.events.broadcaster import EventBroadcaster
from app.events.deps import get_event_broadcaster
from app.events.schemas import QueueEventEnvelope

logger = logging.getLogger(__name__)

router = APIRouter()

# Heartbeat interval for idle SSE connections (proxy keep-alive). Not a setting
# yet — config wiring belongs to a later Phase A.2 task.
SSE_HEARTBEAT_INTERVAL_SECONDS = 30.0

# Per-connection buffer. Overflow disconnects that client only; broadcaster
# callbacks use put_nowait so a slow consumer cannot stall other subscribers.
SSE_CLIENT_QUEUE_MAXSIZE = 64

SSE_HEARTBEAT_FRAME = ": heartbeat\n\n"


def format_sse_event(envelope: QueueEventEnvelope) -> str:
    """Serialize a full ``QueueEventEnvelope`` as one SSE event frame."""
    return (
        f"event: {envelope.event}\n"
        f"id: {envelope.id}\n"
        f"data: {envelope.model_dump_json()}\n"
        f"\n"
    )


def get_sse_heartbeat_interval_seconds() -> float:
    """Heartbeat interval dependency — override in tests for fast idle ticks."""
    return SSE_HEARTBEAT_INTERVAL_SECONDS


async def _event_stream(
    request: Request,
    broadcaster: EventBroadcaster,
    *,
    heartbeat_interval_seconds: float,
) -> AsyncIterator[str]:
    """Yield SSE frames until the client disconnects or the buffer overflows."""
    queue: asyncio.Queue[QueueEventEnvelope | None] = asyncio.Queue(
        maxsize=SSE_CLIENT_QUEUE_MAXSIZE
    )
    closed = asyncio.Event()

    async def on_event(envelope: QueueEventEnvelope) -> None:
        if closed.is_set():
            return
        try:
            queue.put_nowait(envelope)
        except asyncio.QueueFull:
            logger.warning("SSE client queue full; closing slow connection")
            closed.set()
            try:
                queue.put_nowait(None)
            except asyncio.QueueFull:
                pass

    async def watch_disconnect() -> None:
        """Wake the stream loop when the ASGI client disconnects."""
        while not closed.is_set():
            if await request.is_disconnected():
                closed.set()
                try:
                    queue.put_nowait(None)
                except asyncio.QueueFull:
                    pass
                return
            await asyncio.sleep(min(0.25, heartbeat_interval_seconds))

    subscriber_id = broadcaster.subscribe(on_event)
    watcher = asyncio.create_task(watch_disconnect(), name="sse-disconnect-watch")
    try:
        while not closed.is_set():
            try:
                item = await asyncio.wait_for(
                    queue.get(),
                    timeout=heartbeat_interval_seconds,
                )
            except TimeoutError:
                if await request.is_disconnected():
                    break
                yield SSE_HEARTBEAT_FRAME
                continue

            if item is None:
                break
            yield format_sse_event(item)
    except asyncio.CancelledError:
        raise
    except Exception:
        logger.exception("SSE stream failed; closing connection")
    finally:
        closed.set()
        watcher.cancel()
        try:
            await watcher
        except asyncio.CancelledError:
            pass
        broadcaster.unsubscribe(subscriber_id)


@router.get("/stream")
async def stream_queue_events(
    request: Request,
    _: CurrentUser,
    broadcaster: Annotated[EventBroadcaster, Depends(get_event_broadcaster)],
    heartbeat_interval_seconds: Annotated[
        float, Depends(get_sse_heartbeat_interval_seconds)
    ],
) -> StreamingResponse:
    """Open an authenticated Server-Sent Events stream of queue events."""
    return StreamingResponse(
        _event_stream(
            request,
            broadcaster,
            heartbeat_interval_seconds=heartbeat_interval_seconds,
        ),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
